name: Act on release created

# Only trigger, when the Release workflow succeeded
on:
  pull_request:
    types: [opened, reopened]
  #release:
  #  branches:
  #    - master
  #  types:
  #    - published
  #    - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      #- name: call-workflow-in-another-repo
      #  uses: oat-sa/taocloud-ami-luoss/.github/workflows/build_extensions@feat/FUN-884-automatic-build