name: Alert parent repository on push
on: 
  push:
  repository_dispatch:

jobs:
  build:
    name: Dispatch to `other-repo `
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        run: |
          curl -X POST https://api.github.com/repos/oat-sa/taocloud-ami-luoss/actions/workflows/feat/FUN-884-automatic-build/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_TOKEN }} 