name: Alert parent repository on push
on: 
  push:
  repository_dispatch:

jobs:
  build:
    name: Dispatch to `other-repo `
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: token ${{ secrets.GH_TOKEN }}' \
          https://api.github.com/repos/oat-sa/taocloud-ami-luoss/actions/workflows/build_extensions.yml/dispatches \
          -d '{"ref":"feat/FUN-884-automatic-build"}'