name: Alert parent repository on push
on: push

jobs:
  build:
    name: Dispatch to `other-repo `
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: oat-sa/taocloud-ami-luoss@feat/FUN-884-automatic-build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          github_token: ${{ secrets.GH_TOKEN }} 